import { CharacterDef } from "@/types";

export const CHARACTERS: CharacterDef[] = [
  {
    id: "zeno",
    name: "Zeno",
    price: 0,
    currency: "coins",
    primary: "#2ED47A",
    secondary: "#1B8F55",
  },
  {
    id: "vex",
    name: "Vex",
    price: 250,
    currency: "coins",
    primary: "#3EE9F0",
    secondary: "#1E9CA6",
  },
  {
    id: "pip",
    name: "Pip",
    price: 400,
    currency: "coins",
    primary: "#FF6FB5",
    secondary: "#C63E86",
  },
  {
    id: "moko",
    name: "Moko",
    price: 600,
    currency: "coins",
    primary: "#FFD35E",
    secondary: "#D19A2A",
  },
  {
    id: "quix",
    name: "Quix",
    price: 850,
    currency: "coins",
    primary: "#9B59F6",
    secondary: "#6A2FCB",
  },
  {
    id: "nova",
    name: "Nova",
    price: 40,
    currency: "stars",
    primary: "#FF9F43",
    secondary: "#C96E1A",
  },
  {
    id: "glim",
    name: "Glim",
    price: 90,
    currency: "stars",
    primary: "#F5F6FA",
    secondary: "#9AA0C2",
  },
];
